server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/sales_management_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Yty350804201
  thymeleaf:
    prefix:
      classpath: /templates/
  #静态资源访问路径：用于告诉Spring Boot应该在何处查找静态资源文件,查找文件时会依赖于配置的先后顺序依次进行
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

mybatis-plus:
  type-aliases-package: cn.salesManagementSystem.entity
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

define:
  nginx:
    path: \salesManagementSystem\file
    # 项目运行模式，模式为dev时会启用Swagger并关闭登录认证
  model: dev